export const channelDictionary = {
    "downstairs": "shellyplus1-bighouse/command/switch:0",
    "stairs": "buffington-stairs/command/switch:0",
    "masterCloset": "buffington-masterCloset/command/switch:0",
    "kitchen": "buffington-kitchen/command/switch:0",
    "livingroom": "buffington-livingroom/command/switch:0",
    "diningroom": "buffington-diningroom/command/switch:0",
    "jackAndJill": "buffington-jackAndJill/command/switch:0",
    "masterBedroom": "buffington-masterBedroom/command/switch:0",
    "masterBathroom": "buffington-masterBathroom/command/switch:0",
    "laundryRoom": "buffington-laundryRoom/command/switch:0",
    "garage": "buffington-garage/command/switch:0",
    "outside": "buffington-outside/command/switch:0",
    "butlersPantry": "buffington-butlersPantry/command/switch:0",
    "mudroom": "buffington-mudroom/command/switch:0",
    "studio": "buffington-studio/command/switch:0",
  } as const;